version: '3.8'

networks:
  my-network:
    driver: bridge

services:
  app1:
    build: .
    container_name: app1
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
    networks:
      - my-network

  app2:
    build: .
    container_name: app2
    ports:
      - "8081:8080"
    environment:
      - SERVER_PORT=8080
    networks:
      - my-network